import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { isAbsolute, join, normalize, relative, sep } from 'node:path';

/**
 * Where uploaded workbooks, proof documents and generated exports live.
 *
 * SECURITY (spec section 4.4): `storage/` sits outside `public/`, so no static URL
 * reaches any of it. Proofs are customer documents and are served only by
 * `GET /api/proofs/[attachmentId]`, which authorizes the caller first.
 *
 * `storage/` is git-ignored, and in a server deployment it is a mounted volume
 * rather than container-local disk — otherwise every redeploy discards the
 * evidence behind approved corrections.
 */
export const STORAGE_ROOT = join(process.cwd(), 'storage');
export const UPLOADS_DIR = join(STORAGE_ROOT, 'uploads');
export const PROOFS_DIR = join(STORAGE_ROOT, 'proofs');
export const EXPORTS_DIR = join(STORAGE_ROOT, 'exports');

export async function ensureStorageDirs(): Promise<void> {
  await Promise.all([
    mkdir(UPLOADS_DIR, { recursive: true }),
    mkdir(PROOFS_DIR, { recursive: true }),
    mkdir(EXPORTS_DIR, { recursive: true }),
  ]);
}

/**
 * Builds a `YYYY/MM/<uuid>.<ext>` path under the given root and creates the
 * directory.
 *
 * SECURITY: no component of the returned path derives from user input. The
 * filename is a generated UUID and the extension comes from a caller-supplied
 * allowlist, never from the uploaded filename — so path traversal has no
 * surface here at all. The original name is kept in the database column
 * `original_name` for display, which is the only place it is ever used.
 *
 * The date partition is not cosmetic: a single flat directory holding years of
 * proof files degrades badly on most filesystems and makes retention work
 * (deleting a closed year) impossible to do cheaply.
 */
export async function allocateStoragePath(
  root: string,
  extension: string,
  now: Date = new Date(),
): Promise<{ absolutePath: string; relativePath: string }> {
  const year = String(now.getUTCFullYear());
  const month = String(now.getUTCMonth() + 1).padStart(2, '0');
  const ext = extension.replace(/^\.+/, '').toLowerCase();

  const directory = join(root, year, month);
  await mkdir(directory, { recursive: true });

  const fileName = `${randomUUID()}${ext ? `.${ext}` : ''}`;
  const absolutePath = join(directory, fileName);

  return { absolutePath, relativePath: relative(STORAGE_ROOT, absolutePath) };
}

/**
 * Resolves a stored relative path back to an absolute one, refusing anything
 * that escapes `storage/`.
 *
 * Paths in the database were generated by `allocateStoragePath` and are
 * therefore safe by construction — but this function is the last gate before a
 * file is read and handed to a user, and "safe by construction" is a property of
 * today's code, not a guarantee about tomorrow's. A stored path that has been
 * tampered with in the database still cannot escape the storage root.
 */
export function resolveStoredPath(relativePath: string): string {
  if (isAbsolute(relativePath)) {
    throw new Error('Stored paths must be relative to the storage root');
  }

  const resolved = normalize(join(STORAGE_ROOT, relativePath));
  const rel = relative(STORAGE_ROOT, resolved);

  if (rel === '' || rel.startsWith('..') || isAbsolute(rel) || rel.split(sep).includes('..')) {
    throw new Error('Resolved path escapes the storage root');
  }

  return resolved;
}
