import { and, eq, inArray } from 'drizzle-orm';
import { db } from '@/db/client';
import { correctionRequest, salesRecord, uploadBatchRow } from '@/db/schema';
import type { DbTransaction } from '@/lib/audit/log';
import { CANONICAL_FIELDS } from '@/lib/fields';
import type { MasterRecordSnapshot, ValidatedRow } from './types';

/**
 * The staging half of the pipeline — spec section 5.3.
 *
 * Parsing writes here and nowhere else. Nothing touches `sales_record` until an
 * admin commits, which is what makes the mapping screen honest: it shows real
 * parsed values and a real error report from the actual file, produced by the
 * same code that will do the committing, rather than a preview generated by a
 * second code path that might disagree with it.
 */

type Executor = typeof db | DbTransaction;

/**
 * Postgres refuses a statement with more than 65,535 bound parameters, and a
 * staged row binds eight. Batching at 500 keeps a 54,000-row sheet from failing
 * on the insert rather than on anything to do with its content.
 */
const INSERT_CHUNK = 500;

/** `inArray` binds one parameter per element, so the same ceiling applies. */
const LOOKUP_CHUNK = 1000;

function chunk<T>(items: readonly T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

/**
 * Loads what validation needs to know about records that already exist — the
 * current field values and, critically, which fields carry an APPROVED
 * correction and are therefore protected from re-import (spec section 6.8).
 */
export async function loadMasterSnapshots(
  appsNos: readonly string[],
  executor: Executor = db,
): Promise<Map<string, MasterRecordSnapshot>> {
  const snapshots = new Map<string, MasterRecordSnapshot>();
  if (appsNos.length === 0) return snapshots;

  const unique = [...new Set(appsNos)];

  for (const slice of chunk(unique, LOOKUP_CHUNK)) {
    const records = await executor
      .select()
      .from(salesRecord)
      .where(inArray(salesRecord.appsNo, slice));

    for (const record of records) {
      const values: Record<string, string | null> = {};
      for (const field of CANONICAL_FIELDS) {
        const value = (record as Record<string, unknown>)[field.key];
        values[field.key] = value === null || value === undefined ? null : String(value);
      }
      snapshots.set(record.appsNo, {
        id: record.id,
        appsNo: record.appsNo,
        values,
        protectedFields: [],
      });
    }
  }

  const ids = [...snapshots.values()].map((s) => s.id);
  const byId = new Map([...snapshots.values()].map((s) => [s.id, s]));

  for (const slice of chunk(ids, LOOKUP_CHUNK)) {
    const approved = await executor
      .select({ recordId: correctionRequest.recordId, fieldName: correctionRequest.fieldName })
      .from(correctionRequest)
      .where(
        and(inArray(correctionRequest.recordId, slice), eq(correctionRequest.status, 'APPROVED')),
      );

    for (const row of approved) {
      const snapshot = byId.get(row.recordId);
      if (!snapshot) continue;

      for (const field of protectedByCorrectionTo(row.fieldName)) {
        if (!snapshot.protectedFields.includes(field)) snapshot.protectedFields.push(field);
      }
    }
  }

  return snapshots;
}

/**
 * The record columns an approved correction to `fieldName` protects from a
 * re-import.
 *
 * Usually just the field itself. `smId` is the exception: approving a mapping
 * claim writes `smId` AND `smName` together, because spec 7.2 forbids the two
 * from diverging — the name is resolved from the Manpower roster rather than
 * being typed, precisely so they cannot.
 *
 * A correction request only ever NAMES `smId`, so protecting the named field
 * alone left `smName` unguarded. Re-importing the same workbook then held the ID
 * at the gaining rep while overwriting the name back to the losing one, and the
 * record would claim SM_ID C2CM88888 belongs to "Ravi Kumar" — a person who is
 * not that rep. Every downstream reader of `sm_name` (the export, the rep's own
 * record list, mapping notifications) would then name the wrong salesperson,
 * with nothing in the version history explaining why.
 */
function protectedByCorrectionTo(fieldName: string): string[] {
  return fieldName === 'smId' ? ['smId', 'smName'] : [fieldName];
}

/**
 * Replaces a batch's staged rows.
 *
 * Re-validation with a different mapping or date format must not leave the
 * previous attempt's rows behind: they would be committed alongside the new
 * ones, under a mapping the admin explicitly replaced.
 */
export async function stageRows(
  batchId: string,
  rows: readonly ValidatedRow[],
  executor: Executor = db,
): Promise<number> {
  await executor.delete(uploadBatchRow).where(eq(uploadBatchRow.batchId, batchId));

  for (const slice of chunk(rows, INSERT_CHUNK)) {
    await executor.insert(uploadBatchRow).values(
      slice.map((row) => ({
        batchId,
        rowNumber: row.rowNumber,
        raw: row.raw,
        normalized: row.normalized,
        issues: row.issues,
        isDuplicate: row.isDuplicate,
        duplicateOfRow: row.duplicateOfRow,
        status: row.status,
      })),
    );
  }

  return rows.length;
}

export type StagedRow = {
  id: string;
  rowNumber: number;
  raw: Record<string, unknown>;
  normalized: Record<string, string | null>;
  status: 'VALID' | 'INVALID' | 'DUPLICATE' | 'COMMITTED' | 'SKIPPED';
};

/** Reads staged rows back, optionally only those a commit is allowed to touch. */
export async function loadStagedRows(
  batchId: string,
  options: { onlyCommittable?: boolean } = {},
  executor: Executor = db,
): Promise<StagedRow[]> {
  const where = options.onlyCommittable
    ? and(eq(uploadBatchRow.batchId, batchId), eq(uploadBatchRow.status, 'VALID'))
    : eq(uploadBatchRow.batchId, batchId);

  const rows = await executor
    .select({
      id: uploadBatchRow.id,
      rowNumber: uploadBatchRow.rowNumber,
      raw: uploadBatchRow.raw,
      normalized: uploadBatchRow.normalized,
      status: uploadBatchRow.status,
    })
    .from(uploadBatchRow)
    .where(where)
    .orderBy(uploadBatchRow.rowNumber);

  return rows.map((row) => ({
    id: row.id,
    rowNumber: row.rowNumber,
    raw: (row.raw ?? {}) as Record<string, unknown>,
    normalized: (row.normalized ?? {}) as Record<string, string | null>,
    status: row.status,
  }));
}

/** Marks the rows a commit actually wrote, so the batch reads as reconciled. */
export async function markRowsCommitted(
  rowIds: readonly string[],
  executor: Executor = db,
): Promise<void> {
  for (const slice of chunk(rowIds, LOOKUP_CHUNK)) {
    await executor
      .update(uploadBatchRow)
      .set({ status: 'COMMITTED' })
      .where(inArray(uploadBatchRow.id, slice));
  }
}
