import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { Readable } from 'node:stream';
import { NextResponse } from 'next/server';
import { eq, sql } from 'drizzle-orm';
import { z } from 'zod';
import { db } from '@/db/client';
import { excelExport } from '@/db/schema';
import { writeAudit } from '@/lib/audit/log';
import { AuthzError } from '@/lib/auth/errors';
import { requireRole, type SessionUser } from '@/lib/auth/rbac';
import { resolveStoredPath } from '@/lib/storage/paths';

// A cached response would serve one admin's export to the next caller, and the
// download counter would stop moving.
export const dynamic = 'force-dynamic';

const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

/**
 * Builds a Content-Disposition that cannot be steered by the stored name.
 *
 * The name is generated by `exportFileName` and is already tame, but a header
 * value assembled from a database column is a header-injection surface the
 * moment anything else writes that column. The ASCII fallback is stripped to a
 * safe alphabet; RFC 5987 `filename*` carries the real name.
 */
function contentDisposition(fileName: string): string {
  const ascii = fileName.replace(/[^A-Za-z0-9._-]/g, '_') || 'export.xlsx';
  return `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(fileName)}`;
}

/**
 * Streams a generated export — spec section 9.
 *
 * Admin only, checked here. `storage/` sits outside `public/` (spec 4.4), so
 * this handler is the only path to the bytes and the only place the check can
 * live.
 */
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  let actor: SessionUser;
  try {
    actor = await requireRole('admin');
  } catch (error) {
    if (error instanceof AuthzError) {
      return NextResponse.json(
        { error: error.code },
        { status: error.code === 'FORBIDDEN' ? 403 : 401 },
      );
    }
    throw error;
  }

  const { id } = await context.params;

  // A malformed id would otherwise reach Postgres and come back as a 500 that
  // names the uuid type — a 404 is both the honest answer and the quiet one.
  if (!z.uuid().safeParse(id).success) {
    return NextResponse.json({ error: 'NOT_FOUND' }, { status: 404 });
  }

  const [row] = await db
    .select({
      id: excelExport.id,
      fileName: excelExport.fileName,
      storedPath: excelExport.storedPath,
      sha256: excelExport.sha256,
    })
    .from(excelExport)
    .where(eq(excelExport.id, id))
    .limit(1);

  if (!row) return NextResponse.json({ error: 'NOT_FOUND' }, { status: 404 });

  // Never `join(STORAGE_ROOT, row.storedPath)` by hand: resolveStoredPath is
  // the gate that refuses a stored path which has been tampered with into
  // climbing out of the storage root.
  let absolutePath: string;
  try {
    absolutePath = resolveStoredPath(row.storedPath);
  } catch {
    console.error('[export] stored path rejected', row.id);
    return NextResponse.json({ error: 'NOT_FOUND' }, { status: 404 });
  }

  let size: number;
  try {
    size = (await stat(absolutePath)).size;
  } catch {
    // The row survives a lost file so the audit trail keeps its shape; the
    // download is simply gone.
    return NextResponse.json({ error: 'FILE_MISSING' }, { status: 410 });
  }

  // Counted and audited before the stream is handed over: a client that aborts
  // mid-download still requested the file, and an untracked read of an export
  // full of premium figures is the one thing this endpoint exists to record.
  await db.transaction(async (tx) => {
    await tx
      .update(excelExport)
      .set({ downloadCount: sql`${excelExport.downloadCount} + 1` })
      .where(eq(excelExport.id, row.id));

    await writeAudit(
      {
        actor,
        action: 'EXPORT_DOWNLOAD',
        entityType: 'excel_export',
        entityId: row.id,
        metadata: { fileName: row.fileName, sha256: row.sha256, sizeBytes: size },
      },
      tx,
    );
  });

  const body = Readable.toWeb(createReadStream(absolutePath)) as ReadableStream<Uint8Array>;

  return new Response(body, {
    headers: {
      'Content-Type': XLSX_MIME,
      'Content-Length': String(size),
      'Content-Disposition': contentDisposition(row.fileName),
      'Cache-Control': 'no-store, private',
    },
  });
}
