import type { Metadata } from 'next';
import { committedBatches, listExports } from '@/lib/export/queries';
import { describeFilters } from '@/lib/export/schemas';
import { formatDateTime } from '@/lib/format';
import { apiPath } from '@/lib/nav';
import { buttonClass, Card, EmptyState, PageHeader, Table, Td, Th } from '@/components/ui';
import { ExportForm } from './export-form';

export const metadata: Metadata = {
  title: 'Exports · Sales Data Review Portal',
};

// Every generation changes the list, and a cached page would show an admin the
// state before their own export.
export const dynamic = 'force-dynamic';

/**
 * /admin/exports — spec section 9.
 *
 * The page itself is gated by src/app/admin/layout.tsx, which is the documented
 * authorization boundary for this subtree. The mutation and the download do not
 * rely on that: the Server Action and the Route Handler each call requireRole.
 */
export default async function ExportsPage() {
  const [batches, exports] = await Promise.all([committedBatches(), listExports()]);
  const batchNames = new Map(batches.map((b) => [b.id, b.name]));

  return (
    <section>
      <PageHeader
        title="Excel exports"
        description="Generates a new workbook with the master data, an applied-corrections log, and the filters that produced it. The uploaded file is never modified."
      />

      <div className="space-y-6">
        <ExportForm batches={batches} />

        <Card title="Past exports" description="Every generated file stays downloadable.">
          {exports.length === 0 ? (
            <EmptyState
              title="No exports yet"
              description="Generate one above; it will appear here with its row and correction counts."
            />
          ) : (
            <Table>
              <thead>
                <tr>
                  <Th>File</Th>
                  <Th>Filters</Th>
                  <Th className="text-right">Rows</Th>
                  <Th className="text-right">Corrections</Th>
                  <Th>Generated by</Th>
                  <Th>Generated at</Th>
                  <Th className="text-right">Downloads</Th>
                  <Th>
                    <span className="sr-only">Download</span>
                  </Th>
                </tr>
              </thead>
              <tbody>
                {exports.map((row) => (
                  <tr key={row.id}>
                    <Td className="font-medium whitespace-nowrap">{row.fileName}</Td>
                    <Td className="text-slate-600">
                      {describeFilters(row.filters, batchNames).join('; ')}
                    </Td>
                    <Td className="text-right tabular-nums">{row.rowCount.toLocaleString('en-IN')}</Td>
                    <Td className="text-right tabular-nums">{row.correctionCount}</Td>
                    <Td className="whitespace-nowrap">
                      {row.requestedByName ?? row.requestedByEmail ?? '—'}
                    </Td>
                    <Td className="whitespace-nowrap">{formatDateTime(row.createdAt)}</Td>
                    <Td className="text-right tabular-nums">{row.downloadCount}</Td>
                    <Td>
                      {/* A plain anchor, not next/link: the response is a file,
                          and there is no page for the router to navigate to.
                          Which is also why the base path has to be added by
                          hand — see apiPath. */}
                      <a
                        href={apiPath(`/api/exports/${row.id}/download`)}
                        className={buttonClass('secondary', 'px-2.5 py-1.5')}
                      >
                        Download
                      </a>
                    </Td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </Card>
      </div>
    </section>
  );
}
