import type { Metadata } from 'next';
import { requireRoleOrRedirect } from '@/lib/auth/page';
import { committedBatches, listExports } from '@/lib/export/queries';
import { describeFilters } from '@/lib/export/schemas';
import { formatDateTime } from '@/lib/format';
import { periodOptions } from '@/lib/periods/queries';
import { apiPath } from '@/lib/nav';
import { buttonClass, Card, EmptyState, PageHeader, Table, Td, Th } from '@/components/ui';
import { ExportForm } from './export-form';

export const metadata: Metadata = {
  title: 'Exports · Sales Data Review Portal',
};

// Every generation changes the list, and a cached page would show an admin the
// state before their own export.
export const dynamic = 'force-dynamic';

/**
 * /admin/exports — spec section 9.
 *
 * `requireRole` runs here as well as in the layout and again inside the Server
 * Action and the Route Handler. This page was the one admin route that relied on
 * its parent alone, which is the arrangement every sibling's comment warns about:
 * a layout guard protects the render, and a route that trusts it is one refactor
 * away from being reachable without one. The list it renders names every export
 * anyone has generated, so it is worth the line.
 */
export default async function ExportsPage() {
  await requireRoleOrRedirect('admin');

  const [batches, exports, periods] = await Promise.all([
    committedBatches(),
    listExports(),
    periodOptions(),
  ]);
  const batchNames = new Map(batches.map((b) => [b.id, b.name]));

  return (
    <section>
      <PageHeader
        title="Excel exports"
        description="Generates a new workbook with the master data, an applied-corrections log, and the filters that produced it. The uploaded file is never modified."
      />

      <div className="space-y-4">
        <ExportForm batches={batches} periods={periods} />

        <Card title="Past exports" description="Every generated file stays downloadable.">
          {exports.length === 0 ? (
            <EmptyState
              title="No exports yet"
              description="Generate one above; it will appear here with its row and correction counts."
            />
          ) : (
            <Table>
              <thead>
                <tr>
                  <Th>File</Th>
                  <Th>Filters</Th>
                  <Th className="text-right">Rows</Th>
                  <Th className="text-right">Corrections</Th>
                  <Th>Generated by</Th>
                  <Th>Generated at</Th>
                  <Th className="text-right">Downloads</Th>
                  <Th>
                    <span className="sr-only">Download</span>
                  </Th>
                </tr>
              </thead>
              <tbody>
                {exports.map((row) => (
                  <tr key={row.id}>
                    {/* Monospaced: generated names differ only in their
                        timestamp, and that is the part being compared. */}
                    <Td className="font-mono text-[12px] font-medium whitespace-nowrap">
                      {row.fileName}
                    </Td>
                    <Td className="text-[12px] text-slate-600">
                      {describeFilters(row.filters, batchNames).join('; ')}
                    </Td>
                    <Td className="text-right tabular-nums">{row.rowCount.toLocaleString('en-IN')}</Td>
                    <Td className="text-right tabular-nums">{row.correctionCount}</Td>
                    <Td className="text-[12px] whitespace-nowrap text-slate-600">
                      {row.requestedByName ?? row.requestedByEmail ?? '—'}
                    </Td>
                    <Td className="text-[12px] whitespace-nowrap text-slate-600">
                      {formatDateTime(row.createdAt)}
                    </Td>
                    <Td className="text-right tabular-nums">{row.downloadCount}</Td>
                    <Td>
                      {/* A plain anchor, not next/link: the response is a file,
                          and there is no page for the router to navigate to.
                          Which is also why the base path has to be added by
                          hand — see apiPath. */}
                      <a
                        href={apiPath(`/api/exports/${row.id}/download`)}
                        className={buttonClass('secondary', 'px-2.5 py-1.5')}
                      >
                        Download
                      </a>
                    </Td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </Card>
      </div>
    </section>
  );
}
